### ISSUE TITLE
Model does not converge

### ISSUE THREAD

**Issue by MarouaneMan** [nikhilroxtomar/Human-Image-Segmentation-with-DeepLabV3-in-TensorFlow#1]
I tried to run your code base but after a few epochs the loss stops decreasing and the precision stops increasing.
I'm stuck at
**loss: 0.6718 - dice_coef: 0.4866 - iou: 0.3382 - recall: 0.6190 - precision: 0.5947**

Could you check if you can spot the bug ? after a few hours of digging i couldn't success.

I used the same dataset as you mentioned in the Youtube video.

Thank you.

**Comment by MarouaneMan** [comment]
I've made a PR to fix this issue.

**Comment by nikhilroxtomar** [comment]
@MarouaneMan Thanks for the fix in the code.
